        <div class="row">
            <div class="mySlides">
                <img class="mx-auto d-block" src="kepek/sgn1.jpg" alt="N" style="width:100%">
            </div>
            <div class="mySlides">
                <img class="mx-auto d-block" src="kepek/sgn2.jpg" alt="N" style="width:100%">
            </div>
            <div class="mySlides">
                <img class="mx-auto d-block" src="kepek/sgn3.jpg" alt="N" style="width:100%">
            </div>
            <div class="mySlides">
                <div class="mx-auto d-block" id = "clock1"></div>
                <div class="display">
                    <h1 id="name"></h1>
                    <p id="temp"></p>
                    <p id="desc"></p>
                </div>
            </div>
            <div class="mySlides">
                <img class="mx-auto d-block" src="kepek/sgn4.jpg" alt="N" style="width:100%">
            </div>
            <div class="mySlides">
                <img class="mx-auto d-block" src="kepek/sgn5.jpg" alt="N" style="width:100%">
            </div>
            <div class="mySlides">
                <img class="mx-auto d-block" src="kepek/sgn6.jpg" alt="N" style="width:100%">
            </div>
            <div class="mySlides">
                <div class="mx-auto d-block" id = "clock2"></div>
                <div class="display">
                    <h1 id="name2"></h1>
                    <p id="temp2"></p>
                    <p id="desc2"></p>
                </div>
            </div>
            <div class="mySlides">
                <img class="mx-auto d-block" src="kepek/sgn7.jpg" alt="N" style="width:100%">
            </div>
            <div class="mySlides">
                <div class="mx-auto d-block" id = "clock3"></div>
                <div class="display">
                    <h1 id="name3"></h1>
                    <p id="temp3"></p>
                    <p id="desc3"></p>
                </div>
            </div>
        </div>
    </div>
</body>
<script src="script7_10.js"></script>